# Generated by Django 3.1.5 on 2021-01-11 02:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClockApi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hours', models.IntegerField()),
                ('minuts', models.IntegerField()),
                ('angle', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
